'use client';

import { useState, useEffect } from 'react';

interface Insight {
  summary: string;
  diversification: string;
  sectorExposure: string;
  investmentThesis: string;
  riskLevel: string;
}

export default function AIInsights({ portfolioId }: { portfolioId: string }) {
  const [insights, setInsights] = useState<Insight | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchInsights();
  }, [portfolioId]);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/portfolio/${portfolioId}/insights`);
      
      if (!response.ok) {
        // Try to generate new insights
        const generateResponse = await fetch(`/api/portfolio/${portfolioId}/insights`, {
          method: 'POST',
        });
        
        if (!generateResponse.ok) {
          throw new Error('Failed to generate insights');
        }
        
        const data = await generateResponse.json();
        setInsights(data);
      } else {
        const data = await response.json();
        setInsights(data);
      }
    } catch (err) {
      setError('Failed to load insights');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const regenerateInsights = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/portfolio/${portfolioId}/insights`, {
        method: 'POST',
      });
      
      if (!response.ok) throw new Error('Failed to regenerate');
      
      const data = await response.json();
      setInsights(data);
    } catch (err) {
      setError('Failed to regenerate insights');
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="space-y-4 animate-pulse">
        <div className="h-4 bg-slate-700 rounded w-3/4"></div>
        <div className="h-4 bg-slate-700 rounded w-full"></div>
        <div className="h-4 bg-slate-700 rounded w-5/6"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-900/20 border border-red-500 rounded-lg p-4 text-red-300">
        {error}
      </div>
    );
  }

  if (!insights) {
    return (
      <div className="text-gray-400">
        No insights available. Click regenerate to create them.
      </div>
    );
  }

  const getRiskColor = (risk: string) => {
    const lower = risk.toLowerCase();
    if (lower.includes('low')) return 'text-green-400';
    if (lower.includes('medium') || lower.includes('moderate')) return 'text-yellow-400';
    return 'text-red-400';
  };

  return (
    <div className="space-y-6">
      {/* Investment Thesis */}
      <div className="bg-gradient-to-r from-purple-900/30 to-cyan-900/30 border border-purple-500/30 rounded-lg p-4">
        <h3 className="text-lg font-semibold text-purple-300 mb-2 flex items-center gap-2">
          💡 Investment Thesis
        </h3>
        <p className="text-gray-200 italic text-lg">"{insights.investmentThesis}"</p>
      </div>

      {/* Summary */}
      <div>
        <h3 className="text-lg font-semibold text-cyan-300 mb-2 flex items-center gap-2">
          📝 Portfolio Summary
        </h3>
        <p className="text-gray-300 leading-relaxed">{insights.summary}</p>
      </div>

      {/* Risk Level */}
      <div>
        <h3 className="text-lg font-semibold text-yellow-300 mb-2 flex items-center gap-2">
          ⚠️ Risk Assessment
        </h3>
        <p className={`font-semibold text-xl ${getRiskColor(insights.riskLevel)}`}>
          {insights.riskLevel}
        </p>
      </div>

      {/* Diversification */}
      <div>
        <h3 className="text-lg font-semibold text-green-300 mb-2 flex items-center gap-2">
          🎯 Diversification Analysis
        </h3>
        <p className="text-gray-300 leading-relaxed">{insights.diversification}</p>
      </div>

      {/* Sector Exposure */}
      <div>
        <h3 className="text-lg font-semibold text-orange-300 mb-2 flex items-center gap-2">
          🏭 Sector Exposure
        </h3>
        <p className="text-gray-300 leading-relaxed">{insights.sectorExposure}</p>
      </div>

      {/* Regenerate Button */}
      <button
        onClick={regenerateInsights}
        disabled={loading}
        className="w-full bg-slate-700 hover:bg-slate-600 disabled:bg-slate-800 text-white font-medium py-2 px-4 rounded-lg transition"
      >
        {loading ? '🔄 Regenerating...' : '🔄 Regenerate Insights'}
      </button>

      <p className="text-xs text-gray-500 text-center">
        Generated by AI • Last updated: {new Date().toLocaleString()}
      </p>
    </div>
  );
}